/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 
 */
import javax.swing.JButton;
import java.awt.event.ActionListener;


import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;

public class JFrame1 extends javax.swing.JFrame {

    /**
     * Creates new form JFrame1
     */
    private List<String[]> questions = new ArrayList<>();
    public JFrame1() {
        initComponents();
        loadQuestionsFromFile("C:\\Users\\USER\\OneDrive\\Masaüstü\\questions.csv");
    }
     private void loadQuestionsFromFile(String fileName) {
        try {
            BufferedReader reader = new BufferedReader(new FileReader(fileName));
            String line;
            while ((line = reader.readLine()) != null) {
                String[] parts = line.split(",");
                questions.add(parts);
            }
            reader.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(730, 480));

        jPanel1.setMinimumSize(new java.awt.Dimension(730, 480));
        jPanel1.setPreferredSize(new java.awt.Dimension(730, 480));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(255, 0, 102));

        jLabel1.setBackground(new java.awt.Color(102, 102, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("QUESTION");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jLabel1.setRequestFocusEnabled(false);

        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setText("Easy");
        jButton1.setMaximumSize(new java.awt.Dimension(82, 22));
        jButton1.setMinimumSize(new java.awt.Dimension(82, 22));
        jButton1.setPreferredSize(new java.awt.Dimension(82, 22));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setText("Moderate");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setText("Difficult");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jToggleButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jToggleButton1.setText("MENU");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(126, 126, 126))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jToggleButton1)
                .addGap(61, 61, 61)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(175, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 370, 480));

        jPanel3.setPreferredSize(new java.awt.Dimension(370, 480));
        jPanel3.setRequestFocusEnabled(false);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("POINT:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 102));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("0");

        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(87, 269, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(61, 61, 61)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(175, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 360, 480));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
int clickCount = 0;
ActionListener jButton4Listener;
ActionListener jButton6Listener;
ActionListener jButton5Listener;
ActionListener jButton7Listener;

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   String[] selectedQuestion = getRandomQuestionByCategory(1);
    if (selectedQuestion != null) {
        jButton4.setEnabled(true);
        jButton5.setEnabled(true);
        jButton6.setEnabled(true);
        jButton7.setEnabled(true);
        
        String question = selectedQuestion[2];
        String optionA = selectedQuestion[3];
        String optionB = selectedQuestion[4];
        String optionC = selectedQuestion[5];
        String optionD = selectedQuestion[6];
        String correctAnswer = selectedQuestion[7].replaceAll("\"", "");

        jLabel1.setText(question);
        jButton4.setText(optionA);
        jButton6.setText(optionB);
        jButton5.setText(optionC);
        jButton7.setText(optionD);

        ActionListener buttonActionListener = e -> {
            JButton clickedButton = (JButton) e.getSource();
            clickCount++;
            System.out.println("Button clicked " + clickCount + " times");

            String chosenAnswer = "";

            if (clickedButton == jButton4) {
                chosenAnswer = "a";
            } else if (clickedButton == jButton6) {
                chosenAnswer = "b";
            } else if (clickedButton == jButton5) {
                chosenAnswer = "c";
            } else if (clickedButton == jButton7) {
                chosenAnswer = "d";
            }

            checkAnswer(chosenAnswer, correctAnswer);
            System.out.println(chosenAnswer);
        };

        // Önceki ActionListener'ları kaldırma
        if(jButton4Listener != null)
            jButton4.removeActionListener(jButton4Listener);
        if(jButton6Listener != null)
            jButton6.removeActionListener(jButton6Listener);
        if(jButton5Listener != null)
            jButton5.removeActionListener(jButton5Listener);
        if(jButton7Listener != null)
            jButton7.removeActionListener(jButton7Listener);

        // Yeni ActionListener'ları ekleme
        jButton4.addActionListener(jButton4Listener = buttonActionListener);
        jButton6.addActionListener(jButton6Listener = buttonActionListener);
        jButton5.addActionListener(jButton5Listener = buttonActionListener);
        jButton7.addActionListener(jButton7Listener = buttonActionListener);

        System.out.println("Soru: " + question);
        System.out.println("A) " + optionA);
        System.out.println("B) " + optionB);
        System.out.println("C) " + optionC);
        System.out.println("D) " + optionD);
        System.out.println("Doğru Cevap: " + correctAnswer);
    } else {
        System.out.println("Belirtilen kategoride soru bulunamadı.");
    } 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    jButton4.setEnabled(false);
    jButton5.setEnabled(false);
    jButton6.setEnabled(false);
    jButton7.setEnabled(false);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
    jButton4.setEnabled(false);
    jButton5.setEnabled(false);
    jButton6.setEnabled(false);
    jButton7.setEnabled(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
    jButton4.setEnabled(false);
    jButton5.setEnabled(false);
    jButton6.setEnabled(false);
    jButton7.setEnabled(false); 
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
    jButton4.setEnabled(false);
    jButton5.setEnabled(false);
    jButton6.setEnabled(false);
    jButton7.setEnabled(false); 
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        String[] selectedQuestion = getRandomQuestionByCategory(2);
    if (selectedQuestion != null) {
        jButton4.setEnabled(true);
        jButton5.setEnabled(true);
        jButton6.setEnabled(true);
        jButton7.setEnabled(true);
        
        String question = selectedQuestion[2];
        String optionA = selectedQuestion[3];
        String optionB = selectedQuestion[4];
        String optionC = selectedQuestion[5];
        String optionD = selectedQuestion[6];
        String correctAnswer = selectedQuestion[7].replaceAll("\"", "");

        jLabel1.setText(question);
        jButton4.setText(optionA);
        jButton6.setText(optionB);
        jButton5.setText(optionC);
        jButton7.setText(optionD);

        ActionListener buttonActionListener = e -> {
            JButton clickedButton = (JButton) e.getSource();
            clickCount++;
            System.out.println("Button clicked " + clickCount + " times");

            String chosenAnswer = "";

            if (clickedButton == jButton4) {
                chosenAnswer = "a";
            } else if (clickedButton == jButton6) {
                chosenAnswer = "b";
            } else if (clickedButton == jButton5) {
                chosenAnswer = "c";
            } else if (clickedButton == jButton7) {
                chosenAnswer = "d";
            }

            checkAnswer1(chosenAnswer, correctAnswer);
            System.out.println(chosenAnswer);
        };

        // Önceki ActionListener'ları kaldırma
        if(jButton4Listener != null)
            jButton4.removeActionListener(jButton4Listener);
        if(jButton6Listener != null)
            jButton6.removeActionListener(jButton6Listener);
        if(jButton5Listener != null)
            jButton5.removeActionListener(jButton5Listener);
        if(jButton7Listener != null)
            jButton7.removeActionListener(jButton7Listener);

        // Yeni ActionListener'ları ekleme
        jButton4.addActionListener(jButton4Listener = buttonActionListener);
        jButton6.addActionListener(jButton6Listener = buttonActionListener);
        jButton5.addActionListener(jButton5Listener = buttonActionListener);
        jButton7.addActionListener(jButton7Listener = buttonActionListener);

        System.out.println("Soru: " + question);
        System.out.println("A) " + optionA);
        System.out.println("B) " + optionB);
        System.out.println("C) " + optionC);
        System.out.println("D) " + optionD);
        System.out.println("Doğru Cevap: " + correctAnswer);
    } else {
        System.out.println("Belirtilen kategoride soru bulunamadı.");
    } 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
         String[] selectedQuestion = getRandomQuestionByCategory(3);
    if (selectedQuestion != null) {
        jButton4.setEnabled(true);
        jButton5.setEnabled(true);
        jButton6.setEnabled(true);
        jButton7.setEnabled(true);
        
        String question = selectedQuestion[2];
        String optionA = selectedQuestion[3];
        String optionB = selectedQuestion[4];
        String optionC = selectedQuestion[5];
        String optionD = selectedQuestion[6];
        String correctAnswer = selectedQuestion[7].replaceAll("\"", "");

        jLabel1.setText(question);
        jButton4.setText(optionA);
        jButton6.setText(optionB);
        jButton5.setText(optionC);
        jButton7.setText(optionD);

        ActionListener buttonActionListener = e -> {
            JButton clickedButton = (JButton) e.getSource();
            clickCount++;
            System.out.println("Button clicked " + clickCount + " times");

            String chosenAnswer = "";

            if (clickedButton == jButton4) {
                chosenAnswer = "a";
            } else if (clickedButton == jButton6) {
                chosenAnswer = "b";
            } else if (clickedButton == jButton5) {
                chosenAnswer = "c";
            } else if (clickedButton == jButton7) {
                chosenAnswer = "d";
            }

            checkAnswer2(chosenAnswer, correctAnswer);
            System.out.println(chosenAnswer);
        };

        // Önceki ActionListener'ları kaldırma
        if(jButton4Listener != null)
            jButton4.removeActionListener(jButton4Listener);
        if(jButton6Listener != null)
            jButton6.removeActionListener(jButton6Listener);
        if(jButton5Listener != null)
            jButton5.removeActionListener(jButton5Listener);
        if(jButton7Listener != null)
            jButton7.removeActionListener(jButton7Listener);

        // Yeni ActionListener'ları ekleme
        jButton4.addActionListener(jButton4Listener = buttonActionListener);
        jButton6.addActionListener(jButton6Listener = buttonActionListener);
        jButton5.addActionListener(jButton5Listener = buttonActionListener);
        jButton7.addActionListener(jButton7Listener = buttonActionListener);

        System.out.println("Soru: " + question);
        System.out.println("A) " + optionA);
        System.out.println("B) " + optionB);
        System.out.println("C) " + optionC);
        System.out.println("D) " + optionD);
        System.out.println("Doğru Cevap: " + correctAnswer);
    } else {
        System.out.println("Belirtilen kategoride soru bulunamadı.");
    } 
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        // TODO add your handling code here:
        GameHomePage.score = jLabel3.getText(); // Puanı 100 olarak ayarla
        DiamondGame.time = jLabel3.getText(); 
        GameHomePage homePage = new GameHomePage(); // Yeni bir GameHomePage örneği oluştur
        homePage.setVisible(true); // Ekranı görünür yap
        dispose();// Şu anki pencereyi kapat
    }//GEN-LAST:event_jToggleButton1ActionPerformed
     
private String[] getRandomQuestionByCategory(int category) {
    List<String[]> categoryQuestions = new ArrayList<>();
    for (String[] question : questions) {
        int cat;
        try {
            cat = Integer.parseInt(question[0].trim().replaceAll("\"", ""));
        } catch (NumberFormatException e) {
            continue; // Geçersiz sayısal formatı olanları atla
        }
        if (cat == category) {
            categoryQuestions.add(question);
        }
    }
    if (categoryQuestions.isEmpty()) {
        return new String[]{"Sorular Bitti"};
    }
    Random random = new Random();
    return categoryQuestions.get(random.nextInt(categoryQuestions.size()));
}

private void checkAnswer(String selectedOption, String correctAnswer) {
    correctAnswer = correctAnswer.replaceAll("\"", ""); // Gelen cevapta olabilecek gereksiz karakterleri kaldır
    if (selectedOption.equalsIgnoreCase(correctAnswer)) { // Büyük-küçük harf duyarlılığını kaldırarak karşılaştırma yap
        int currentScore = Integer.parseInt(jLabel3.getText()); // Mevcut puanı al
        int newScore = currentScore + 10; // Doğru cevap için 10 puan ekle
        jLabel3.setText(Integer.toString(newScore)); // Yeni puanı güncelle
        System.out.println("Doğru cevap! Yeni puan: " + newScore);
    } else {
        System.out.println("Yanlış cevap!");
    }
}
private void checkAnswer1(String selectedOption, String correctAnswer) {
    correctAnswer = correctAnswer.replaceAll("\"", ""); // Gelen cevapta olabilecek gereksiz karakterleri kaldır
    if (selectedOption.equalsIgnoreCase(correctAnswer)) { // Büyük-küçük harf duyarlılığını kaldırarak karşılaştırma yap
        int currentScore = Integer.parseInt(jLabel3.getText()); // Mevcut puanı al
        int newScore = currentScore + 30; // Doğru cevap için 10 puan ekle
        jLabel3.setText(Integer.toString(newScore)); // Yeni puanı güncelle
        System.out.println("Doğru cevap! Yeni puan: " + newScore);
    } else {
        System.out.println("Yanlış cevap!");
    }
}

private void checkAnswer2(String selectedOption, String correctAnswer) {
    correctAnswer = correctAnswer.replaceAll("\"", ""); // Gelen cevapta olabilecek gereksiz karakterleri kaldır
    if (selectedOption.equalsIgnoreCase(correctAnswer)) { // Büyük-küçük harf duyarlılığını kaldırarak karşılaştırma yap
        int currentScore = Integer.parseInt(jLabel3.getText()); // Mevcut puanı al
        int newScore = currentScore + 50; // Doğru cevap için 10 puan ekle
        jLabel3.setText(Integer.toString(newScore)); // Yeni puanı güncelle
        System.out.println("Doğru cevap! Yeni puan: " + newScore);
    } else {
        System.out.println("Yanlış cevap!");
    }
}
public String getScore() {
    return jLabel3.getText();
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrame1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrame1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
